package Cartpage;

import BestSellerpage.BestSeller_page;
import Homepage.Home_page;
import Menupage.Menu_page;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @ALESSA_AFIQAH_012020021640
 */
public class Cart_page extends javax.swing.JFrame implements MouseListener
{
    /**
     * Creates new form Cart_page
     */
    public Cart_page() //constructor
    {
        initComponents();
        
        fiction_1.addMouseListener(this);
        fiction_2.addMouseListener(this);
        fiction_3.addMouseListener(this);
        fiction_4.addMouseListener(this);
        fiction_5.addMouseListener(this);
        
        nonfiction_1.addMouseListener(this);
        nonfiction_2.addMouseListener(this);
        nonfiction_3.addMouseListener(this);
        nonfiction_4.addMouseListener(this);
        nonfiction_5.addMouseListener(this);
        nonfiction_6.addMouseListener(this);
        
        magazine_1.addMouseListener(this);
        magazine_2.addMouseListener(this);
        magazine_3.addMouseListener(this);
        magazine_4.addMouseListener(this);
        magazine_5.addMouseListener(this);
        
        reference_1.addMouseListener(this);
        reference_2.addMouseListener(this);
        reference_3.addMouseListener(this);
        reference_4.addMouseListener(this);
        reference_5.addMouseListener(this);
    }
    
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_1 = new javax.swing.JPanel();
        menu_label = new javax.swing.JLabel();
        bestseller_label = new javax.swing.JLabel();
        exit_label = new javax.swing.JLabel();
        minimize_label = new javax.swing.JLabel();
        cart_label = new javax.swing.JLabel();
        logout_label = new javax.swing.JLabel();
        panel_2 = new javax.swing.JPanel();
        label_1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fiction_1 = new javax.swing.JLabel();
        fiction_2 = new javax.swing.JLabel();
        fiction_3 = new javax.swing.JLabel();
        fiction_4 = new javax.swing.JLabel();
        fiction_5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nonfiction_1 = new javax.swing.JLabel();
        nonfiction_2 = new javax.swing.JLabel();
        nonfiction_3 = new javax.swing.JLabel();
        nonfiction_4 = new javax.swing.JLabel();
        nonfiction_5 = new javax.swing.JLabel();
        nonfiction_6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        magazine_3 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        magazine_4 = new javax.swing.JLabel();
        magazine_5 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        magazine_1 = new javax.swing.JLabel();
        magazine_2 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        reference_2 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        reference_3 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        reference_4 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        reference_5 = new javax.swing.JLabel();
        reference_1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollpanel_1 = new javax.swing.JScrollPane();
        cartTable_1 = new javax.swing.JTable();
        delete_button = new javax.swing.JButton();
        total_button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        total_text_1 = new javax.swing.JTextField();
        checkout_button_1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes_textarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_1.setBackground(new java.awt.Color(255, 51, 51));
        panel_1.setPreferredSize(new java.awt.Dimension(172, 41));

        menu_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menu_label.setText("MENU");
        menu_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_labelMouseClicked(evt);
            }
        });

        bestseller_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bestseller_label.setText("BESTSELLER");
        bestseller_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bestseller_labelMouseClicked(evt);
            }
        });

        exit_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exit_label.setText("X");
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
        });

        minimize_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        minimize_label.setText("_");
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });

        cart_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cart_label.setText("CART");
        cart_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_labelMouseClicked(evt);
            }
        });

        logout_label.setText("LOG OUT");
        logout_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logout_label)
                .addGap(29, 29, 29)
                .addComponent(menu_label)
                .addGap(34, 34, 34)
                .addComponent(bestseller_label)
                .addGap(42, 42, 42)
                .addComponent(cart_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize_label, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(menu_label)
                        .addComponent(bestseller_label)
                        .addComponent(cart_label)
                        .addComponent(logout_label))
                    .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exit_label)
                        .addComponent(minimize_label)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel_2.setBackground(new java.awt.Color(255, 204, 204));
        panel_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cart Page", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        label_1.setBackground(new java.awt.Color(255, 255, 255));
        label_1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_1.setText("Category:");

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Loveless");

        jLabel3.setText("RM 31.92");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Broken Stars");

        jLabel5.setText("RM 45.90");

        jLabel15.setText("RM 86.95");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel14.setText("The Good, the Bad, and");

        jLabel69.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel69.setText("the Little Bit Stupid");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Just My Luck");

        jLabel16.setText("RM 62.90");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("Pumpkin Heads");

        jLabel17.setText("RM 55.92");

        fiction_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/fiction_1.PNG"))); // NOI18N

        fiction_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/fiction_2.PNG"))); // NOI18N

        fiction_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/fiction_3.PNG"))); // NOI18N

        fiction_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/fiction_4.PNG"))); // NOI18N

        fiction_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/fiction_5.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(193, 193, 193)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel69)
                                    .addComponent(jLabel15))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(406, 406, 406)
                                .addComponent(fiction_4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fiction_1)
                                .addGap(41, 41, 41)
                                .addComponent(fiction_2)
                                .addGap(62, 62, 62)
                                .addComponent(fiction_3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(fiction_5)))
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fiction_1)
                    .addComponent(fiction_2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiction_4)
                            .addComponent(fiction_3)
                            .addComponent(fiction_5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel69)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fiction", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        nonfiction_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/nonfiction_1.PNG"))); // NOI18N

        nonfiction_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/nonfiction_2.PNG"))); // NOI18N

        nonfiction_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/nonfiction_3.PNG"))); // NOI18N

        nonfiction_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/nonfiction_4.PNG"))); // NOI18N

        nonfiction_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/nonfiction_5.PNG"))); // NOI18N

        nonfiction_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/nonfiction_6.PNG"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel22.setText("Brief Answer to");

        jLabel23.setText("RM 59.90");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel24.setText("the Big Questions");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel25.setText("The Math of Life ");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel26.setText("and Death");

        jLabel27.setText("RM 129.90");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel28.setText("You Look Like a Thing");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel29.setText("and I Love You");

        jLabel30.setText("RM 136.90");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel31.setText("Science: Vintage Minis");

        jLabel32.setText("RM 22.90");

        jLabel33.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel33.setText("Sloth");

        jLabel34.setText("RM 55.90");

        jLabel35.setText("RM 74.90");

        jLabel36.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel36.setText("The World Almanac");

        jLabel37.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel37.setText("and Book of Facts 2020");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(nonfiction_1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nonfiction_2)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(nonfiction_3)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nonfiction_4)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34))
                                .addGap(48, 48, 48))
                            .addComponent(nonfiction_5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel30))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(nonfiction_6)
                    .addComponent(jLabel37))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nonfiction_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nonfiction_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nonfiction_6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(jLabel33))
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel35)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nonfiction_3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nonfiction_1)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(nonfiction_2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Non Fiction", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        magazine_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/magezine_3.PNG"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel39.setText("UNNERVING");

        magazine_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/magezine_4.PNG"))); // NOI18N

        magazine_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/magezine_5.PNG"))); // NOI18N

        jLabel42.setText("RM 37.60");

        jLabel43.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel43.setText("tacenda");

        jLabel44.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel44.setText("40 Timeless Knits");

        jLabel45.setText("RM 39.41");

        jLabel46.setText("RM 121.90");

        jLabel48.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel48.setText("Robert Heinecken");

        jLabel49.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel49.setText("Cookies Perfection");

        jLabel50.setText("RM 52.90");

        magazine_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/magezine_1.PNG"))); // NOI18N

        magazine_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/magezine_2.PNG"))); // NOI18N

        jLabel53.setText("RM 126.07");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(magazine_5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(magazine_1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(magazine_2)
                            .addComponent(jLabel49)
                            .addComponent(jLabel53))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(magazine_3)
                            .addComponent(jLabel42))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(magazine_4)
                            .addComponent(jLabel45))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel50))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(magazine_1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(magazine_2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel53))
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(magazine_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(magazine_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel50)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(magazine_3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Magazines", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel47.setText("Chemistry");

        reference_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/reference_2.PNG"))); // NOI18N

        jLabel51.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel51.setText("Tingkatan 4");

        jLabel54.setText("RM 35.95");

        reference_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/reference_3.PNG"))); // NOI18N

        jLabel52.setText("RM 11.00");

        jLabel55.setText("RM 28.00");

        jLabel40.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel40.setText("Success Sains SPM");

        jLabel56.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel56.setText("Modul A+ SPM Sejarah");

        reference_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/reference_4.PNG"))); // NOI18N

        jLabel58.setText("RM 10.32");

        reference_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/reference_5.PNG"))); // NOI18N

        reference_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small size/reference_1.PNG"))); // NOI18N

        jLabel59.setText("RM 37.90");

        jLabel60.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel60.setText("Matematik Tambahan");

        jLabel61.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel61.setText("Tingkatan 4 & 5");

        jLabel62.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel62.setText("Focus SPM Biologi");

        jLabel63.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel63.setText("Tingkatan 4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addComponent(jLabel51)
                    .addComponent(jLabel55)
                    .addComponent(reference_1))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62)
                            .addComponent(reference_2)
                            .addComponent(jLabel61))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(reference_3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reference_4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel47)))))
                    .addComponent(jLabel54))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(reference_5)
                    .addComponent(jLabel58)
                    .addComponent(jLabel63))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reference_1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reference_2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel40))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel59))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel55)
                                .addComponent(jLabel58))
                            .addComponent(jLabel54)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reference_4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(reference_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel56))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel63)
                                        .addGap(1, 1, 1))))
                            .addComponent(reference_3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("References", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("List of Book(s)");

        cartTable_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK NAME", "CATEGORY", "PRICE (RM)", "QUANTITY", "TOTAL (RM)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanel_1.setViewportView(cartTable_1);

        delete_button.setText("DELETE");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        total_button.setText("TOTAL");
        total_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpanel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete_button)
                        .addGap(18, 18, 18)
                        .addComponent(total_button)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(delete_button)
                    .addComponent(total_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel12.setText("TOTAL (RM):");

        total_text_1.setEditable(false);
        total_text_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        total_text_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        checkout_button_1.setBackground(new java.awt.Color(255, 102, 51));
        checkout_button_1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        checkout_button_1.setForeground(new java.awt.Color(255, 255, 255));
        checkout_button_1.setText("CHECK OUT");
        checkout_button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkout_button_1ActionPerformed(evt);
            }
        });

        notes_textarea.setEditable(false);
        notes_textarea.setBackground(new java.awt.Color(255, 255, 0));
        notes_textarea.setColumns(20);
        notes_textarea.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        notes_textarea.setRows(5);
        notes_textarea.setText("**Notes\n1)Please click the\n  book image to add \n  the list of book(s)\n\n2)Before click check \n  out button,please \n  click the \"TOTAL\" \n  button.");
        jScrollPane1.setViewportView(notes_textarea);

        javax.swing.GroupLayout panel_2Layout = new javax.swing.GroupLayout(panel_2);
        panel_2.setLayout(panel_2Layout);
        panel_2Layout.setHorizontalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total_text_1)
                            .addComponent(checkout_button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_2Layout.createSequentialGroup()
                                .addComponent(label_1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel_2Layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        panel_2Layout.setVerticalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_2Layout.createSequentialGroup()
                .addComponent(label_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(checkout_button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
            .addComponent(panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void cart_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_labelMouseClicked
        JOptionPane.showMessageDialog(null, "You're already in Cart Page");
    }//GEN-LAST:event_cart_labelMouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete","Delete", JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            model = (DefaultTableModel) cartTable_1.getModel();
            try
            {
                int SelectedRowIndex = cartTable_1.getSelectedRow();
                model.removeRow(SelectedRowIndex);
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Please select the list before you delete");
            }
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void total_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_buttonActionPerformed
        double sum=0;
        for(double i=0; i<cartTable_1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(cartTable_1.getValueAt((int) i, 4).toString());
        }
            
        total_text_1.setText(Double.toString(sum));
    }//GEN-LAST:event_total_buttonActionPerformed

    private void logout_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_labelMouseClicked
        Home_page hp = new Home_page();
        hp.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logout_labelMouseClicked

    private void checkout_button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkout_button_1ActionPerformed
        String filepath = "C:\\Users\\user\\Desktop\\Receipt.txt";
        File file = new File(filepath);
        try
        {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for (int i=0; i<cartTable_1.getRowCount(); i++)
            {
                for (int j=0; j<cartTable_1.getColumnCount(); j++)
                {
                    bw.write(cartTable_1.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
            
        //Appearance of payment frame
        String totalprice = total_text_1.getText();
        new Payment_page(totalprice).setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_checkout_button_1ActionPerformed

    private void menu_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_labelMouseClicked
        Menu_page hp = new Menu_page();
        hp.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_menu_labelMouseClicked

    private void bestseller_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bestseller_labelMouseClicked
        BestSeller_page hp = new BestSeller_page();
        hp.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bestseller_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestseller_label;
    private javax.swing.JTable cartTable_1;
    private javax.swing.JLabel cart_label;
    private javax.swing.JButton checkout_button_1;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel fiction_1;
    private javax.swing.JLabel fiction_2;
    private javax.swing.JLabel fiction_3;
    private javax.swing.JLabel fiction_4;
    private javax.swing.JLabel fiction_5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_1;
    private javax.swing.JLabel logout_label;
    private javax.swing.JLabel magazine_1;
    private javax.swing.JLabel magazine_2;
    private javax.swing.JLabel magazine_3;
    private javax.swing.JLabel magazine_4;
    private javax.swing.JLabel magazine_5;
    private javax.swing.JLabel menu_label;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JLabel nonfiction_1;
    private javax.swing.JLabel nonfiction_2;
    private javax.swing.JLabel nonfiction_3;
    private javax.swing.JLabel nonfiction_4;
    private javax.swing.JLabel nonfiction_5;
    private javax.swing.JLabel nonfiction_6;
    private javax.swing.JTextArea notes_textarea;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JLabel reference_1;
    private javax.swing.JLabel reference_2;
    private javax.swing.JLabel reference_3;
    private javax.swing.JLabel reference_4;
    private javax.swing.JLabel reference_5;
    private javax.swing.JScrollPane scrollpanel_1;
    private javax.swing.JButton total_button;
    private javax.swing.JTextField total_text_1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) 
    {
        if(e.getSource() == fiction_1)
        {
            String name = "Loveless";
            String category = "Fiction";
            double price = 31.92;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == fiction_2)
        {
            String name = "Broken_Stars";
            String category = "Fiction";
            double price = 45.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == fiction_3)
        {
            String name = "The_Good,The_Bad_and_The_Little_Bit_Stupid";
            String category = "Fiction";
            double price = 86.95;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == fiction_4)
        {
            String name = "Pumpkin_Heads";
            String category = "Fiction";
            double price = 62.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == fiction_5)
        {
            String name = "Just_My_Luck";
            String category = "Fiction";
            double price = 55.92;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == nonfiction_1)
        {
            String name = "Brief_Answer_to_The_Big_Questions";
            String category = "Non_Fiction";
            double price = 59.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == nonfiction_2)
        {
            String name = "The_Math_of_Life_and_Death";
            String category = "Non_Fiction";
            double price = 129.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == nonfiction_3)
        {
            String name = "You_Look_Like_a_Thing_and_I_Love_You";
            String category = "Non_Fiction";
            double price = 136.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == nonfiction_4)
        {
            String name = "Science:Vintage_Minis";
            String category = "Non_Fiction";
            double price = 22.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == nonfiction_5)
        {
            String name = "Sloth";
            String category = "Non_Fiction";
            double price = 55.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == nonfiction_6)
        {
            String name = "The_Wold_Almanac_and_Book_of_Fact_2020";
            String category = "Non_Fiction";
            double price = 74.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == magazine_1)
        {
            String name = "40_Timeless_Knits";
            String category = "Magazine";
            double price = 121.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == magazine_2)
        {
            String name = "Cookies_Perfection";
            String category = "Magazine";
            double price = 126.07;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == magazine_3)
        {
            String name = "Unnerving";
            String category = "Magazine";
            double price = 37.60;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == magazine_4)
        {
            String name = "tacenda";
            String category = "Magazine";
            double price = 39.41;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == magazine_5)
        {
            String name = "Robert_Hienecken";
            String category = "Magazine";
            double price = 52.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == reference_1)
        {
            String name = "Matematik_Tambahan_Tingkatan_4";
            String category = "Reference";
            double price = 28;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == reference_2)
        {
            String name = "Focus_Spm_Biologi_Tingkatan_4&5";
            String category = "Reference";
            double price = 35.95;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == reference_3)
        {
            String name = "Success_Sains_SPM";
            String category = "Reference";
            double price = 37.90;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == reference_4)
        {
            String name = "Chemistry";
            String category = "Reference";
            double price = 11;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
        
        else if(e.getSource() == reference_5)
        {
            String name = "Modul_A+_SPM_Sejarah_Tingkatan_4";
            String category = "Reference";
            double price = 10.32;
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the quantity"));
            double total = (double) (price*quantity);
            
            model = (DefaultTableModel)cartTable_1.getModel();
            model.addRow(new Object[]
            {
                name,
                category,
                price,
                quantity,
                total,
            });
        }
    }

    @Override
    public void mousePressed(MouseEvent e) 
    {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) 
    {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) 
    {
        
    }

    @Override
    public void mouseExited(MouseEvent e) 
    {
        
    }
}
